version: "3.8"
   
services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    
  http_server:
    build: 
      context: ./server
    container_name: http_server
    command: python3 http_server.py
    depends_on:
      - db
    restart: unless-stopped

  proxy:
    image: nginx
    container_name: reverse_proxy
    ports:
      - 8080:8080
    volumes:
      - ./server/nginx_config:/etc/nginx
    depends_on:
      - http_server
    restart: unless-stopped
